### PR TITLE
Add 413 code info to README.md

### PR DESCRIPTION
**Pull request by ranger-turtle**
There have been no changes since creation of the #65 just for update of README.md and I do not know what else. So I have made changes to README.md I found needed after adding 413 code support.

### CODE REVIEW

**Comment by AKlaus** [comment]
Sorry, I already did a lot of renaming of `Payload Too Large` to `Content Too Large` in PR #65 along with adding it to the README and other minor changes.
Hence, I have to decline this PR.

**Comment by AKlaus** [comment]
@ranger-turtle, hey mate,
I just noticed that you aren't listed in the project contributors, as the account the original PR came from is shown as inactive/deleted/etc.
If you want, we can arrange a small PR from your current account (I can guide you there), so you get listed in the contributors.

**Comment by ranger-turtle** [comment]
> @ranger-turtle, hey mate, I just noticed that you aren't listed in the project contributors, as the account the original PR came from is shown as inactive/deleted/etc. If you want, we can arrange a small PR from your current account (I can guide you there), so you get listed in the contributors.

How I can do it?

**Comment by AKlaus** [comment]
I just raised #69 PR. So the idea is
1. You can mimic some or all of those changes and submit your PR.
2. I'll merge yours instead of mine.

It should be enough, I guess.

**Pull request closed without merging**
